# -*- coding: utf-8 -*-
"""Phase1_Data_Engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KNUD6j0p-SAa7yB4EvzgCn9F1LjU-WM9

# Quantitative Alpha Research & Portfolio Intelligence Platform

Institutional-grade long/short equity research infrastructure using Python, quantitative factor analytics, risk intelligence, and portfolio optimization.

# Phase 1 — Institutional Data & Universe Engine
"""

!pip install yfinance arch --quiet

import pandas as pd
import numpy as np
import yfinance as yf
import warnings

warnings.filterwarnings("ignore")

NIFTY50_TICKERS = [
    "RELIANCE.NS",
    "TCS.NS",
    "INFY.NS",
    "HDFCBANK.NS",
    "ICICIBANK.NS",
    "SBIN.NS",
    "LT.NS",
    "ITC.NS",
    "AXISBANK.NS",
    "KOTAKBANK.NS"
]

data = yf.download(
    NIFTY50_TICKERS,
    start="2018-01-01",
    auto_adjust=True,
    progress=False
)

prices = data["Close"]

prices.head()

print("Shape:", prices.shape)
print("\nMissing Values:")
print(prices.isna().sum())

prices = prices.ffill(limit=5)

prices.isna().sum()

simple_returns = prices.pct_change().dropna()

log_returns = np.log(prices / prices.shift(1)).dropna()

summary_stats = pd.DataFrame({
    "CAGR": ((prices.iloc[-1] / prices.iloc[0]) ** (252 / len(prices)) - 1),
    "Volatility": log_returns.std() * np.sqrt(252),
    "Sharpe": (log_returns.mean() / log_returns.std()) * np.sqrt(252)
})

summary_stats

"""# Phase 2 — Multi-Factor Analytics Engine"""

momentum_6m = prices.pct_change(126).iloc[-1]

momentum_12m = prices.pct_change(252).iloc[-1]

momentum_df = pd.DataFrame({
    "Momentum_6M": momentum_6m,
    "Momentum_12M": momentum_12m
})

momentum_df

rolling_vol = log_returns.std() * np.sqrt(252)

volatility_df = pd.DataFrame({
    "Annualized_Volatility": rolling_vol
})

volatility_df

cumulative_returns = (1 + simple_returns).cumprod()

rolling_max = cumulative_returns.cummax()

drawdowns = cumulative_returns / rolling_max - 1

max_drawdown = drawdowns.min()

drawdown_df = pd.DataFrame({
    "Max_Drawdown": max_drawdown
})

drawdown_df

risk_free_rate = 0.06

excess_returns = log_returns - risk_free_rate / 252

sharpe_ratio = (
    excess_returns.mean() /
    excess_returns.std()
) * np.sqrt(252)

downside_std = log_returns.where(log_returns < 0).std()

sortino_ratio = (
    excess_returns.mean() /
    downside_std
) * np.sqrt(252)

risk_metrics_df = pd.DataFrame({
    "Sharpe": sharpe_ratio,
    "Sortino": sortino_ratio
})

risk_metrics_df

factor_table = pd.concat([
    summary_stats,
    momentum_df,
    volatility_df,
    drawdown_df,
    risk_metrics_df
], axis=1)

factor_table

momentum_6m = prices.pct_change(126).iloc[-1]

momentum_12m = prices.pct_change(252).iloc[-1]

momentum_df = pd.DataFrame({
    "Momentum_6M": momentum_6m,
    "Momentum_12M": momentum_12m
})

momentum_df

"""Phase 2B: Factor Ssoring Engine"""

selected_factors = [
    "CAGR",
    "Momentum_12M",
    "Sortino"
]

risk_factors = [
    "Annualized_Volatility",
    "Max_Drawdown"
]

factor_scores = pd.DataFrame(index=factor_table.index)

for factor in selected_factors:
    factor_scores[factor + "_Score"] = (
        factor_table[factor]
        .rank(pct=True)
    )

for factor in risk_factors:
    factor_scores[factor + "_Score"] = (
        1 - factor_table[factor].rank(pct=True)
    )

factor_scores

factor_scores["Composite_Alpha_Score"] = (
    factor_scores.mean(axis=1)
)

factor_scores = factor_scores.sort_values(
    "Composite_Alpha_Score",
    ascending=False
)

factor_scores

"""PHASE 3 — Long/Short Portfolio Construction Engine"""

top_n = 3

long_portfolio = factor_scores.head(top_n)

short_portfolio = factor_scores.tail(top_n)

print("LONG PORTFOLIO")
display(long_portfolio)

print("\nSHORT PORTFOLIO")
display(short_portfolio)

long_weights = np.repeat(
    1 / top_n,
    top_n
)

short_weights = np.repeat(
    -1 / top_n,
    top_n
)

long_weights

long_returns = simple_returns[
    long_portfolio.index
]

short_returns = simple_returns[
    short_portfolio.index
]

strategy_returns = (
    long_returns.mean(axis=1)
    -
    short_returns.mean(axis=1)
)

strategy_cumulative = (
    1 + strategy_returns
).cumprod()

strategy_cumulative.tail()

benchmark = simple_returns["RELIANCE.NS"]

benchmark_cumulative = (
    1 + benchmark
).cumprod()

import matplotlib.pyplot as plt

plt.figure(figsize=(14,7))

plt.plot(
    strategy_cumulative,
    label="Long/Short Strategy"
)

plt.plot(
    benchmark_cumulative,
    label="Benchmark"
)

plt.title("Strategy vs Benchmark")

plt.legend()

plt.grid(True)

plt.show()

"""# Phase 4 — Institutional Rolling Rebalance Backtest Engine"""

monthly_prices = prices.resample("M").last()

monthly_returns = monthly_prices.pct_change().dropna()

monthly_prices.head()

rolling_momentum = monthly_prices.pct_change(12)

strategy_returns = []

strategy_dates = []

top_n = 3

for i in range(12, len(monthly_returns)-1):

    signal_date = monthly_returns.index[i]

    next_date = monthly_returns.index[i+1]

    factor_signal = rolling_momentum.loc[signal_date]

    ranked = factor_signal.sort_values(
        ascending=False
    )

    long_stocks = ranked.head(top_n).index

    short_stocks = ranked.tail(top_n).index

    next_returns = monthly_returns.loc[next_date]

    long_return = next_returns[long_stocks].mean()

    short_return = next_returns[short_stocks].mean()

    portfolio_return = long_return - short_return

    strategy_returns.append(portfolio_return)

    strategy_dates.append(next_date)

rolling_strategy = pd.Series(
    strategy_returns,
    index=strategy_dates
)

rolling_cumulative = (
    1 + rolling_strategy
).cumprod()

rolling_cumulative.tail()

benchmark_monthly = monthly_returns["RELIANCE.NS"]

benchmark_cumulative = (
    1 + benchmark_monthly.loc[rolling_cumulative.index]
).cumprod()

plt.figure(figsize=(14,7))

plt.plot(
    rolling_cumulative,
    label="Rolling Long/Short Strategy"
)

plt.plot(
    benchmark_cumulative,
    label="Benchmark"
)

plt.title("Institutional Rolling Backtest")

plt.legend()

plt.grid(True)

plt.show()

"""# Phase 5 — Advanced Quant Intelligence Layer"""

rolling_volatility = (
   rolling_strategy.rolling(6).std()
    * np.sqrt(12)
)

rolling_volatility.tail()

rolling_sharpe = (
    rolling_strategy.rolling(6).mean()
    /
    rolling_strategy.rolling(6).std()
) * np.sqrt(12)

rolling_sharpe.tail()

rolling_cumulative_curve = (
    1 + rolling_strategy
).cumprod()

rolling_peak = rolling_cumulative_curve.cummax()

rolling_drawdown = (
    rolling_cumulative_curve /
    rolling_peak
) - 1

rolling_drawdown.tail()

"""Institutional Risk Intelligence Dashboard"""

# Install Plotly
!pip install plotly

import plotly.graph_objects as go
from plotly.subplots import make_subplots

fig = make_subplots(
    rows=3,
    cols=1,
    shared_xaxes=True,
    vertical_spacing=0.08,
    subplot_titles=(
        "Rolling Volatility",
        "Rolling Sharpe Ratio",
        "Rolling Drawdown"
    )
)

# Rolling Volatility
fig.add_trace(
    go.Scatter(
        x=rolling_volatility.index,
        y=rolling_volatility,
        mode='lines',
        name='Rolling Volatility',
        line=dict(width=3)
    ),
    row=1,
    col=1
)

# Rolling Sharpe
fig.add_trace(
    go.Scatter(
        x=rolling_sharpe.index,
        y=rolling_sharpe,
        mode='lines',
        name='Rolling Sharpe',
        line=dict(width=3)
    ),
    row=2,
    col=1
)

# Rolling Drawdown
fig.add_trace(
    go.Scatter(
        x=rolling_drawdown.index,
        y=rolling_drawdown,
        mode='lines',
        name='Rolling Drawdown',
        fill='tozeroy',
        line=dict(width=3)
    ),
    row=3,
    col=1
)

fig.update_layout(
    height=1000,
    width=1400,
    title={
        'text': 'Institutional Quant Risk Intelligence Dashboard',
        'x': 0.5,
        'xanchor': 'center'
    },
    template='plotly_dark',
    hovermode='x unified',
    showlegend=True
)

fig.update_xaxes(
    title_text='Date',
    showgrid=True
)

fig.update_yaxes(
    title_text='Annualized Volatility',
    row=1,
    col=1
)

fig.update_yaxes(
    title_text='Sharpe Ratio',
    row=2,
    col=1
)

fig.update_yaxes(
    title_text='Drawdown',
    row=3,
    col=1
)

fig.show()

"""Phase 6 — Market Regime Detection Engine"""

market_volatility = (
    monthly_returns.std(axis=1)
)

vol_threshold = market_volatility.median()

vol_threshold

market_regime = pd.Series(
    np.where(
        market_volatility > vol_threshold,
        "High Volatility",
        "Low Volatility"
    ),
    index=market_volatility.index
)

market_regime.tail()

market_regime.value_counts()

regime_numeric = np.where(
    market_regime == "High Volatility",
    1,
    0
)

plt.figure(figsize=(14,5))

plt.plot(
    market_regime.index,
    regime_numeric,
    linewidth=3
)

plt.yticks(
    [0,1],
    ["Low Volatility","High Volatility"]
)

plt.title("Market Regime Detection")

plt.grid(True)

plt.show()

"""# Phase 7 — Dynamic Regime-Based Portfolio Allocation"""

regime_exposure = pd.Series(
    np.where(
        market_regime == "High Volatility",
        0.5,
        1.0
    ),
    index=market_regime.index
)

regime_exposure.tail()

aligned_exposure = regime_exposure.loc[
    rolling_strategy.index
]

dynamic_strategy_returns = (
    rolling_strategy
    * aligned_exposure
)

dynamic_cumulative = (
    1 + dynamic_strategy_returns
).cumprod()

dynamic_cumulative.tail()

fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=rolling_cumulative.index,
        y=rolling_cumulative,
        mode='lines',
        name='Static Strategy',
        line=dict(width=3)
    )
)

fig.add_trace(
    go.Scatter(
        x=dynamic_cumulative.index,
        y=dynamic_cumulative,
        mode='lines',
        name='Dynamic Regime Strategy',
        line=dict(width=3)
    )
)

fig.add_trace(
    go.Scatter(
        x=benchmark_cumulative.index,
        y=benchmark_cumulative,
        mode='lines',
        name='Benchmark',
        line=dict(width=3)
    )
)

fig.update_layout(
    title='Dynamic Regime-Based Portfolio Allocation',
    template='plotly_dark',
    height=700,
    width=1400,
    hovermode='x unified'
)

fig.show()

"""# Phase 8 — Institutional Factor Optimization Engine"""

factor_weights = {
    "CAGR_Score": 0.20,
    "Momentum_12M_Score": 0.30,
    "Sortino_Score": 0.20,
    "Annualized_Volatility_Score": 0.15,
    "Max_Drawdown_Score": 0.15
}

weighted_alpha_score = pd.Series(
    0,
    index=factor_scores.index,
    dtype=float
)

for factor, weight in factor_weights.items():

    weighted_alpha_score += (
        factor_scores[factor]
        * weight
    )

weighted_alpha_score

optimized_rankings = pd.DataFrame({
    "Weighted_Alpha_Score": weighted_alpha_score
})

optimized_rankings = optimized_rankings.sort_values(
    "Weighted_Alpha_Score",
    ascending=False
)

optimized_rankings

comparison_df = pd.DataFrame({
    "Equal_Weight_Score":
        factor_scores["Composite_Alpha_Score"],

    "Weighted_Alpha_Score":
        weighted_alpha_score
})

comparison_df

fig = go.Figure()

fig.add_trace(
    go.Bar(
        x=list(factor_weights.keys()),
        y=list(factor_weights.values()),
        text=list(factor_weights.values()),
        textposition='auto'
    )
)

fig.update_layout(
    title='Institutional Factor Weight Architecture',
    template='plotly_dark',
    height=600,
    width=1200
)

fig.show()

"""# Phase 9 — Machine Learning Alpha Layer"""

!pip install scikit-learn

from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_squared_error

from sklearn.metrics import r2_score

ml_data = factor_table.copy()

ml_data = ml_data.dropna()

ml_data

future_3m_return = (
    prices.pct_change(63)
    .iloc[-1]
)

ml_data = factor_table.copy()

ml_data["Future_Return"] = future_3m_return

ml_data = ml_data.dropna()

print("Rows:", len(ml_data))

ml_data

features = [
    "CAGR",
    "Momentum_12M",
    "Annualized_Volatility",
    "Max_Drawdown",
    "Sortino"
]

X = ml_data[features]

y = ml_data["Future_Return"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)

print("Training rows:", len(X_train))
print("Testing rows:", len(X_test))

model = RandomForestRegressor(
    n_estimators=200,
    max_depth=5,
    random_state=42
)

model.fit(X_train, y_train)

predictions = model.predict(X_test)

predictions

mse = mean_squared_error(y_test, predictions)

r2 = r2_score(y_test, predictions)

print("Mean Squared Error:", round(mse, 6))

print("R2 Score:", round(r2, 4))

feature_importance = pd.DataFrame({
    "Factor": features,
    "Importance": model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    "Importance",
    ascending=False
)

feature_importance

import plotly.express as px

fig = px.bar(
    feature_importance,
    x="Factor",
    y="Importance",
    title="Institutional Factor Importance Model",
    template="plotly_dark",
    color="Importance"
)

fig.show()

"""Phase 10 — Monte Carlo + Stress Testing + VaR Engine"""

strategy_returns = (
    long_returns.mean(axis=1)
    -
    short_returns.mean(axis=1)
)

strategy_returns.head()

portfolio_returns = strategy_returns.dropna()

portfolio_returns.describe()

import numpy as np

simulations = 1000

time_horizon = 252

mc_paths = []

mean_return = portfolio_returns.mean()

volatility = portfolio_returns.std()

for i in range(simulations):

    simulated_returns = np.random.normal(
        mean_return,
        volatility,
        time_horizon
    )

    simulated_path = (
        1 + simulated_returns
    ).cumprod()

    mc_paths.append(simulated_path)

import matplotlib.pyplot as plt

plt.style.use("dark_background")

plt.figure(figsize=(14,7))

for path in mc_paths[:100]:
    plt.plot(path, alpha=0.15)

plt.title("Monte Carlo Portfolio Simulation")

plt.xlabel("Trading Days")

plt.ylabel("Portfolio Value")

plt.grid(True)

plt.show()

var_95 = np.percentile(
    portfolio_returns,
    5
)

cvar_95 = portfolio_returns[
    portfolio_returns <= var_95
].mean()

print("95% Daily VaR:", round(var_95, 4))

print("95% CVaR:", round(cvar_95, 4))

plt.figure(figsize=(14,7))

plt.hist(
    portfolio_returns,
    bins=40,
    alpha=0.7
)

plt.axvline(
    var_95,
    color='red',
    linestyle='dashed',
    linewidth=2,
    label='95% VaR'
)

plt.title("Portfolio Tail Risk Distribution")

plt.legend()

plt.grid(True)

plt.show()

